### ISSUE TITLE
the preprocessed dataset is not applicable

### ISSUE THREAD

**Issue by andys0975** [UARK-AICV/SAM3D#2]
I downloaded your preprocessed dataset on Google drive and tried to train the model using training_scripts.
However it keep show the error:
RuntimeError: 
Could not find a task with the ID %d. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:...

All four datasets got the same error.

**Comment by tanbuinhat** [comment]
Hi, sorry for late response!

Have you run the code yet?
