### ISSUE TITLE
The BRATS dataset and checkpoints are not available 

### ISSUE THREAD

**Issue by zia-khan351** [UARK-AICV/SAM3D#3]
download the preprocessed dataset at [Google Drive](https://drive.google.com/drive/folders/1N8FAxEH0QExkqQbPT2oy2DrzUfIaRDMx?usp=drive_link).
 Put the checkpoint in the ./checkpoints folder.

The BraTS weight can be downloaded at [Google Drive](https://drive.google.com/file/d/1jxWSlK1Zy_gBY_XO3xh6ydaLthqDh5Tm/view?usp=drive_link).
[The BRATS dataset is not available ](![BRATSissue](https://github.com/UARK-AICV/SAM3D/assets/110028917/742366f4-3257-4e24-8956-510d487b3dd0))

**Comment by tanbuinhat** [comment]
Hi, sorry for our mistake!

We've already updated the checkpoint path!
